Update requirements.txt
Bumped openai dependency to resolve conflict:
262.9 ERROR: Cannot install -r src/requirements.txt (line 50) and openai==0.28.0 because these package versions have conflicting dependencies.
262.9
262.9 The conflict is caused by:
262.9     The user requested openai==0.28.0
262.9     semantic-router 0.0.51 depends on openai<2.0.0 and >=1.10.0
262.9
262.9 To fix this you could try to:
262.9 1. loosen the range of package versions you've specified
262.9 2. remove package versions to allow pip attempt to solve the dependency conflict
262.9
262.9 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
Dockerfile:53
--------------------
  52 |     # Create virtual environment and install dependencies
  53 | >>> RUN python3 -m venv /env && \
  54 | >>>     /env/bin/pip install --no-cache-dir --use-pep517 -r src/requirements.txt
  55 |
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m venv /env &&     /env/bin/pip install --no-cache-dir --use-pep517 -r src/requirements.txt" did not complete successfully: exit code: 1
Docker build failed. Exiting...