Update requirements.txt
Resolves dependency conflict:
133.7 The conflict is caused by:
133.7     The user requested aiohttp==3.8.5
133.7     openai 0.28.0 depends on aiohttp
133.7     semantic-router 0.0.51 depends on aiohttp<4.0.0 and >=3.9.5
133.7
133.7 To fix this you could try to:
133.7 1. loosen the range of package versions you've specified
133.7 2. remove package versions to allow pip attempt to solve the dependency conflict
133.7
133.7 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
Dockerfile:53
--------------------
  52 |     # Create virtual environment and install dependencies
  53 | >>> RUN python3 -m venv /env && \
  54 | >>>     /env/bin/pip install --no-cache-dir --use-pep517 -r src/requirements.txt
  55 |
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m venv /env &&     /env/bin/pip install --no-cache-dir --use-pep517 -r src/requirements.txt" did not complete successfully: exit code: 1
Docker build failed. Exiting...